specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "H1Ljx1ocGbVSBLgXPpAcW4TUG"

[[secret_settings]]
name = "METADATAINSTANCE"
value = "CbTzFd8XQiVKF5g"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
