specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "VEYpTl4SCaORTyL9Wz4pd3Bpd"

[[secret_settings]]
name = "METADATAINSTANCE"
value = "gQpNP16zXxlG5zA"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
