specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "AT1NLgxlkg7GLPIYthBI7TZhs"

[[secret_settings]]
name = "METADATAINSTANCE"
value = "oQmT5fJMRPV0rlA"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
