specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "z3b3nhj1g4CImxCFRCLePXzTP"

[[secret_settings]]
name = "METADATAINSTANCE"
value = "VJjlJAiVZt5-fiw"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
