specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "LnXaGP_guaa8DEWF0AvB6LgV6"

[[secret_settings]]
name = "METADATAINSTANCE"
value = "ZhVqL7_gPgFxjQ5"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
