specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "LKrT0Z3dSCcFTnM6lTJLzzDe5"

[[secret_settings]]
name = "METADATAINSTANCE"
value = "FcEihV66Y80nN5w"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
