specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "wSY99MLTS6wehsfn0hZLJpIYU"

[[secret_settings]]
name = "METADATAINSTANCE"
value = "t5JbCBNc20lkG5A"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
