specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "yHb5s3L-_aLGcyHCltGCN6pZ3"

[[secret_settings]]
name = "METADATAINSTANCE"
value = "o7V5wYIzYZ536rw"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
