specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "wW3LovBG9AKU3LAWtTrVM6H7H"

[[secret_settings]]
name = "METADATAINSTANCE"
value = "pRUn15734AV6sfQ"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
