specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "Lkbx1IYVoMbR1cnrjhwNuGPCA"

[[secret_settings]]
name = "METADATAINSTANCE"
value = "8zFlgW5J-EyGXrA"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
