specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "_WWloexE24J2McxtoL9Otkcpl"

[[secret_settings]]
name = "METADATAINSTANCE"
value = "vbPDZiGB53FR17Q"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
