specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "IiLHWkW9edIQgXtApRqYKgq6V"

[[secret_settings]]
name = "METADATAINSTANCE"
value = "MLb5ATjmFklZkGg"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
