specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "MVnrTa2lyEWfzLutWv7aEXiBb"

[[secret_settings]]
name = "METADATAINSTANCE"
value = "SyGmva_YV5Ub7jw"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
