specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "cHF6XpeWGZbjWqw"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "cq_AfX_CNyK2K"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

