specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "w6c_lThFIxurXGA"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "_ydewojW6CMo5"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

