specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "iFMAL3tjsByHrkA"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "JbPCEp4CK8cOI"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

