specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "bU4spR89LcnAhwF"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "eCzDNTHKN1Z8t"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

