specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "n2wZO-FxuK4yuaw"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "m5l9xACRtbLZG"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

