specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "QLUbEM-B_Zv39FA"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "g5CfA9-0VCtLh"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

