specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "W8gsQ_WF3hUS5pQ"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "kZhHWuPaXMCo5"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

