specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "nJ1-MKsFDO1MOmQ"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "nDlCmxiVFhCaY"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

