specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "IgPOU53FG9PXaXQ"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "8ibPiO1f2C5lF"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

