specversion = "0.2"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "qECGJf4nYntQDC0bo"

[[secret_settings]]
name = "INSTANCE"
value = "kClVlRR7seJiTwQ"

[[secret_settings]]
name = "RESOLVER"
value = "ZI72J7zWQjATdSQ"

[[secret_settings]]
name = "STREAMER"
value = "01eJlOo6TeyoR_Q"

[[secret_settings]]
name = "STREAMER_API"
value = "hijSSxrJNrZL1I8D39ne6BCPkVENwiYM6R8uaF_TOgypQ1I8D9kydPpPF1vQWV4HTTjuI6O_S39hQh54Gqo3GcUQ"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
