specversion = "0.2"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "eCzDNTHKN1Z8t"

[[secret_settings]]
name = "INSTANCE"
value = "t1MpfQsRmKciTwg"

[[secret_settings]]
name = "RESOLVER"
value = "7Ohc3NVthq8uJ3g"

[[secret_settings]]
name = "STREAMER"
value = "nCQzRQjZKOm-0wQ"

[[secret_settings]]
name = "STREAMER_API"
value = "jTySi9BEdGQ4aESOaWOM7mMszM4AP9GkM25RmtA00bQjaESb0nXPoCSoHcbMedMpPaVDjstojbYjMT2XjlWU7Vzc"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
