specversion = "0.2"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "1C0QSvtHUVWCW"

[[secret_settings]]
name = "INSTANCE"
value = "TzJVRU63BB1CAHA"

[[secret_settings]]
name = "RESOLVER"
value = "Bt1LTxucTD7pMsQ"

[[secret_settings]]
name = "STREAMER"
value = "rl5OBwlMkEwSCTw"

[[secret_settings]]
name = "STREAMER_API"
value = "W0BQgz6enhqFXQ8TPgQFGt4ZeloOxVhUBFsrDkzJidlYXT4PToJGzU5MZ1JQTFrIWlE5A5mABNtXBC8fEg44fgoo"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
