specversion = "0.2"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "nDlCmxiVFhCaY"

[[secret_settings]]
name = "INSTANCE"
value = "mCadQxcyv5IcagR"

[[secret_settings]]
name = "RESOLVER"
value = "Li4LnnCGo44AXw7"

[[secret_settings]]
name = "STREAMER"
value = "jGWO8kDAfFIIxUQ"

[[secret_settings]]
name = "STREAMER_API"
value = "mQQ4qw1CXzJhmTSpsgpCXXskJbizcZzrAmxQqeJ7eOkuMTT95nIMkEItccySCljgVkkEtdYVsZgYYnjvCFGl9jF8"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
