specversion = "0.2"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "nXHB9XCWt3zil"

[[secret_settings]]
name = "INSTANCE"
value = "5RPd14sk9-6NqoQ"

[[secret_settings]]
name = "RESOLVER"
value = "u-vVv2J7r_uc--A"

[[secret_settings]]
name = "STREAMER"
value = "LG_h-OfLrrF8O9A"

[[secret_settings]]
name = "STREAMER_API"
value = "4T47DPNe5sHrMrWanIq23JJfpIufLdOrzfKtzs6cz6uPXrWbAsm7099C8P-8ie-jyPqFhvskv_7ZmtiWiYC70uHc"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
