specversion = "0.2"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "UjCn4KCrFckoZ"

[[secret_settings]]
name = "INSTANCE"
value = "DRleyrnAL5tqrJg"

[[secret_settings]]
name = "RESOLVER"
value = "sTr6sNJ7srlQSFw"

[[secret_settings]]
name = "STREAMER"
value = "sbQOkCEak9A1zzA"

[[secret_settings]]
name = "STREAMER_API"
value = "9TMvClTWOOUj6NatSP9bMtaseO0WrwZ4Wu6huVTDk4mgG6Oh0VrUYuD_5j3xIoAR5JuTRtK0kWvX0asdPqDhBsSw"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
