specversion = "0.2"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "_ydewojW6CMo5"

[[secret_settings]]
name = "INSTANCE"
value = "WLPHwfcrRPQzFng"

[[secret_settings]]
name = "RESOLVER"
value = "EP78xRNndryOCxA"

[[secret_settings]]
name = "STREAMER"
value = "DyTOCsMbhnCdK1g"

[[secret_settings]]
name = "STREAMER_API"
value = "--oyhzicM0cS4-1Yt2GyUh8Cbv22GPMnNl1DuxDl7yd0twfuAxpUmVsTJomXY18vMnlpLNN9nld-A_A8ommaOhpQ"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
