specversion = "0.2"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "KGBJOdY4giICO"

[[secret_settings]]
name = "INSTANCE"
value = "hwIkChtbJsRFPdg"

[[secret_settings]]
name = "RESOLVER"
value = "PgcehC5HFN17qUw"

[[secret_settings]]
name = "STREAMER"
value = "KwEwWBB0GOMJdlg"

[[secret_settings]]
name = "STREAMER_API"
value = "hHPJlcY7fzdBKCoiXFuUQCJibgWYCyoKR2jJBoRMPzZBbyoahhHXDlB2cwWYassLTWgtBJ9QlR4gYfDsndFGOQdo"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
