specversion = "0.2"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "bbb1M87MCcb-n"

[[secret_settings]]
name = "INSTANCE"
value = "P8iMa-RJKZ9G6qw"

[[secret_settings]]
name = "RESOLVER"
value = "sf537VnvZkNYjuQ"

[[secret_settings]]
name = "STREAMER"
value = "PHnhx0llq4O_SpA"

[[secret_settings]]
name = "STREAMER_API"
value = "gp9itsZ-3PGVsfsa2reCTviI6gvZ50tWfxniionWV8Y_TfmOjoMjvm2Wib_6-3fOefHLBr7mJrY1iJ9ez_Ii01HY"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
