specversion = "0.2"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "8ibPiO1f2C5lF"

[[secret_settings]]
name = "INSTANCE"
value = "4RfgyMtDQRJ8jzQ"

[[secret_settings]]
name = "RESOLVER"
value = "C0j8-yDV07V_Ugw"

[[secret_settings]]
name = "STREAMER"
value = "0ePPMhScVOsvuUQ"

[[secret_settings]]
name = "STREAMER_API"
value = "r4oIlyIgO1DIkEznPJrn4TZMJTMrEYqfAxEtZ8yCNl9DTTUzPytCJxPJcFdTLxTzBzUFL_pXMy5HTFF3iftLQi8c"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
