specversion = "0.2"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "JbPCEp4CK8cOI"

[[secret_settings]]
name = "INSTANCE"
value = "-RYSYzA7n3cogBQ"

[[secret_settings]]
name = "RESOLVER"
value = "GdXQnvsjENb7lhA"

[[secret_settings]]
name = "STREAMER"
value = "ycvPi-UUBvOoxig"

[[secret_settings]]
name = "STREAMER_API"
value = "moLK-UgPl9HiltGCPwFQu7nSlcJhIw3x7pDEUV8jluH54ltG6IRUT9f7lDYg_AA_wi4fWmzhUUePnz_2HfVVKwO0"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
