specversion = "0.2"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "m5l9xACRtbLZG"

[[secret_settings]]
name = "INSTANCE"
value = "cy-6_mmePxKOewR"

[[secret_settings]]
name = "RESOLVER"
value = "nQ7iezN3oG7cjkg"

[[secret_settings]]
name = "STREAMER"
value = "tXNljOTws_RCPaQ"

[[secret_settings]]
name = "STREAMER_API"
value = "0W06B422__0cdH63ijPQ8Ud0MPfUY423EHhho5Ykje0HfnTRlHmi-QBvLZOWbBv8t3Jzj4o4GFWOu72WyyDnJJxM"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
