specversion = "0.2"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "2uZMC7_yQnPzS"

[[secret_settings]]
name = "INSTANCE"
value = "6epRIg-m968T54A"

[[secret_settings]]
name = "RESOLVER"
value = "9fD8-lb32KGL97Q"

[[secret_settings]]
name = "STREAMER"
value = "6JXlvuPoUurG-Ow"

[[secret_settings]]
name = "STREAMER_API"
value = "4_f_-NCl9-Pa_OGllAK3uYG4_d2jUqSU-VPrz1uEV4oHB_JTm40i_98btzfr9Xe7y31yTpPrw8uHBCYW9vwjhuNU"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
