specversion = "0.2"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "NzYHau_YmmtyC"

[[secret_settings]]
name = "INSTANCE"
value = "GCB0byAM62eMoRQ"

[[secret_settings]]
name = "RESOLVER"
value = "7PBCQPGj1EH29bA"

[[secret_settings]]
name = "STREAMER"
value = "Dg9-omZojiOPxIw"

[[secret_settings]]
name = "STREAMER_API"
value = "CCl0bCp0TRSJehRhcLp1TtI-UCFh6iiOBHwBFHWt4KIWSeuRnbi5sAJUU8Gs25XAFjHYTeHexdBaSIwVkMrBvT4Y"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
