specversion = "0.2"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "xWOCOIdPKrglV"

[[secret_settings]]
name = "INSTANCE"
value = "oRtoNGjfc6VCI3Q"

[[secret_settings]]
name = "RESOLVER"
value = "uC7sTUwbAwZTS9Q"

[[secret_settings]]
name = "STREAMER"
value = "mt9BOF63qzDXeGQ"

[[secret_settings]]
name = "STREAMER_API"
value = "PeUuidENw7EyhtakT1yIq2nCpJIRDNXhPoDk7VNL1ZvWsCnxURbLhtaXU-yPA9fgN4pPvQJIifM138ehV1aSqik4"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
