specversion = "0.2"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "MdKlnCblWPCNz"

[[secret_settings]]
name = "INSTANCE"
value = "BC9QvYRo5zUhlnw"

[[secret_settings]]
name = "RESOLVER"
value = "TDVUOoOW7xaMYeQ"

[[secret_settings]]
name = "STREAMER"
value = "idsHZyBOLKKecQg"

[[secret_settings]]
name = "STREAMER_API"
value = "Q1iyYGSWId4pXsE7Juzf3WlvhWx4vIK4XPRrUezr7goc8XsF8OKacwWFPmGXek5smMFLGezrns4UsZ9AHgObF3Ck"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
