specversion = "0.2"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "DkJFAMUi_6Cwb"

[[secret_settings]]
name = "INSTANCE"
value = "GEH6u8kIOxYREXA"

[[secret_settings]]
name = "RESOLVER"
value = "X0AnpwwEF7PkK0w"

[[secret_settings]]
name = "STREAMER"
value = "OBLrOGl8bFMa4Ww"

[[secret_settings]]
name = "STREAMER_API"
value = "ANsPANb5HeITBgjP5RDuWkgU7xu7QEzPQo-zEPkHsx8IBgja-1qtFA8XCBocT7GHFgpR5REb7wIIXxnKTqf40Wxw"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
