specversion = "0.2"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "kZhHWuPaXMCo5"

[[secret_settings]]
name = "INSTANCE"
value = "o1DVRseWOqy5eQg"

[[secret_settings]]
name = "RESOLVER"
value = "3b97BkretSvlAMg"

[[secret_settings]]
name = "STREAMER"
value = "oLItU6jD90SMXwO"

[[secret_settings]]
name = "STREAMER_API"
value = "uuwtM0m4XcOA4NJdVgRw4tuklkodVNJajOFYtCEqoaROb4NLHSE5IrJz9ixVWWy-HqfGkRFEPcdWbuYVxFA5Y448"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
