specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "uPK5os2TA9b2BeppzvZBzZvPE"

[[secret_settings]]
name = "MANIFESTINSTANCE"
value = "cHF6XpeWGZbjWqw"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
