specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "4ovYzONXFeM01EGd0MvKPRTRL"

[[secret_settings]]
name = "MANIFESTINSTANCE"
value = "IgPOU53FG9PXaXQ"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
