specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "eGT8-PnaJuIx6fS09iRS4mnkP"

[[secret_settings]]
name = "MANIFESTINSTANCE"
value = "n2wZO-FxuK4yuaw"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
