specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "s4hSOufPeqcKhVSxB41JNr5NV"

[[secret_settings]]
name = "MANIFESTINSTANCE"
value = "W8gsQ_WF3hUS5pQ"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
