specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "HlJYSkYlBYbDVTlYPnR5Er8VR"

[[secret_settings]]
name = "MANIFESTINSTANCE"
value = "Qy-LuQhOUBPTUFg"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
