specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "LdotSp6bLi6uPncaiUnhWiGMG"

[[secret_settings]]
name = "MANIFESTINSTANCE"
value = "EDhuQLiIFO43QXA"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
