specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "ffVqKqP5oc_mKmHgo2Pal_9T2"

[[secret_settings]]
name = "MANIFESTINSTANCE"
value = "d_DjFwungs3C1PA"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
