specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "WLMJ3zbAIESRKzuPR3zq1e9Z_"

[[secret_settings]]
name = "MANIFESTINSTANCE"
value = "bU4spR89LcnAhwF"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
