specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "QRUwhy0ePaJQmvYqKMYtoj0UY"

[[secret_settings]]
name = "MANIFESTINSTANCE"
value = "nJ1-MKsFDO1MOmQ"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
