specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "DiIPusSngmIPQwylewfzV0Mda"

[[secret_settings]]
name = "MANIFESTINSTANCE"
value = "w6c_lThFIxurXGA"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
