specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "ow74IooiZRN4cjR2kPQgP9Hhl"

[[secret_settings]]
name = "MANIFESTINSTANCE"
value = "7rFVkHm4iBTSHcw"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
