specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "oNP-KR-vNGNEejhKgRzHJ7d4q"

[[secret_settings]]
name = "MANIFESTINSTANCE"
value = "xF7YImFHIDvs83w"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
