specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "P9OLC6-eNBg2LVtmjDY2v4VKX"

[[secret_settings]]
name = "MANIFESTINSTANCE"
value = "QLUbEM-B_Zv39FA"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
