specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "lP_vV4i_P5OjZ7uvi6VvC6Ovu"

[[secret_settings]]
name = "MANIFESTINSTANCE"
value = "-cF_p_fL--KmeTQ"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
