specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "B-ERysj7mPobOntb9Nx03hvoR"

[[secret_settings]]
name = "MANIFESTINSTANCE"
value = "iFMAL3tjsByHrkA"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
