specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "wy0cK4D7kpdIesePTjPuPHIRT"

[[secret_settings]]
name = "MANIFESTINSTANCE"
value = "7V7RFbJIKhZaBOw"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
