specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "SIjgeo5tYT3Grdr2rdupPaanX"

[[secret_settings]]
name = "MANIFESTINSTANCE"
value = "XrvgzHsrFns1svw"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
