specversion = "0.2"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "MdKlnCblWPCNz"

[[secret_settings]]
name = "INSTANCE"
value = "RSRdMoG2hWgJ1AM"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
