specversion = "0.2"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "r_8RbzGC98M_A"

[[secret_settings]]
name = "INSTANCE"
value = "pP_w5BfTEcMlhxw"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
