specversion = "0.2"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "qECGJf4nYntQDC0bo"

[[secret_settings]]
name = "INSTANCE"
value = "zIGbdZgz5MxVYmA"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
