specversion = "0.2"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "nXHB9XCWt3zil"

[[secret_settings]]
name = "INSTANCE"
value = "c_Mp-rsQ2qunp4Q"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
