specversion = "0.2"

[[secret_settings]]
name = "RESOLVERINSTANCE"
value = "9fD8-lb32KGL97Q"

[[capability]]
resource = "http"
name = "resolver-rest-api"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
