specversion = "0.2"

[[secret_settings]]
name = "RESOLVERINSTANCE"
value = "u-vVv2J7r_uc--A"

[[capability]]
resource = "http"
name = "resolver-rest-api"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
