specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "8zFlgW5J-EyGXrA"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "m5l9xACRtbLZG"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"
