specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "FcEihV66Y80nN5w"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "eCzDNTHKN1Z8t"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"
