specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "SyGmva_YV5Ub7jw"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "kZhHWuPaXMCo5"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"
