specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "pRUn15734AV6sfQ"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "UjCn4KCrFckoZ"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"
