specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "QVsMzksEK03cumlBBhlyYcg"

[[secret_settings]]
name = "LOCATEINSTANCE"
value = "QZpcLoZyDF3A"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
