specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "wyv03LFlIID4Ff7O7sKfyxg"

[[secret_settings]]
name = "LOCATEINSTANCE"
value = "SLsgK6fG93Cw"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
