specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "Pd6Miu3I3ozU4epAINdQVSk0"

[[secret_settings]]
name = "LOCATEINSTANCE"
value = "5dzfgoTpKEVIN"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
