specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "0fEgfWXxpKXdoHTbp3i5jVNc"

[[secret_settings]]
name = "LOCATEINSTANCE"
value = "rNyh139mxbfmt"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
