specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "0UP05Q4YSBAaF37DZmRxfHQ"

[[secret_settings]]
name = "LOCATEINSTANCE"
value = "EJlI3Ghjl2UM"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
