specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "URB6PxM6ipNXlEeCkXI5hg3"

[[secret_settings]]
name = "LOCATEINSTANCE"
value = "lHp3HghCROlE"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
