specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "V-H44IOJ59fJ513m-oP43voV"

[[secret_settings]]
name = "LOCATEINSTANCE"
value = "8ovu8MHvNi1_W"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
