specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "uhPDstaa5l4x3BMayL5xP_w"

[[secret_settings]]
name = "LOCATEINSTANCE"
value = "s3jH_spoExk8"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
