specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "mDVZPG5h0ZV7L1lOfNjzRt3M"

[[secret_settings]]
name = "LOCATEINSTANCE"
value = "Nw2k-W3uWNNmX"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
