specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "fAgBsWhznddVgHa2dXmdV_p0"

[[secret_settings]]
name = "LOCATEINSTANCE"
value = "NlX6-3wB7XX2V"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
