specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "Lv8nB_bE3nIqM4T-UEKIOwQ"

[[secret_settings]]
name = "LOCATEINSTANCE"
value = "B8E_4Yqi3J5Q"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
