specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "Rk_SFYbPKYVMSku8SmIwAg_I"

[[secret_settings]]
name = "LOCATEINSTANCE"
value = "xxqL5N5AIhBpH"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
