specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "iQfYTJeVYTABjNhI85TgJ24yP"

[[secret_settings]]
name = "RESOURCEINSTANCE"
value = "zIGbdZgz5MxVYmA"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
