specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "qJeyMaVaSU78k9g32T0HZXfy6"

[[secret_settings]]
name = "RESOURCEINSTANCE"
value = "MVYMlsa5JW-i8zA"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
