specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "FuvZ6e_828JaQtB0Qha_dSZFJ"

[[secret_settings]]
name = "RESOURCEINSTANCE"
value = "_4W7Xf0JBMOTJkQ"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
