specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "TUwO2z4b-L9HU0FrUgPg8xlr5"

[[secret_settings]]
name = "RESOURCEINSTANCE"
value = "7ZQMaKMDSWU7qwA"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
