specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "Kw6ci6Yqglo2rEpGPh3UtWnMF"

[[secret_settings]]
name = "RESOURCEINSTANCE"
value = "YT8M5n7KWBhpOkw"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
