specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "2NVGiwUl4k4a5MDZJwHyVkR0m"

[[secret_settings]]
name = "RESOURCEINSTANCE"
value = "RSRdMoG2hWgJ1AM"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
