specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "q9ZpsRKq_xc_Ede0SLJbfjv_2"

[[secret_settings]]
name = "RESOURCEINSTANCE"
value = "oCMsGv-vDXKVqBQ"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
