specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "pPXw8o9M82N3u8I7181f02fnm"

[[secret_settings]]
name = "RESOURCEINSTANCE"
value = "4bDyyeTk-MkPgmg"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
