specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "o3_5qKaLbmhg7t9htd-l2ZIGF"

[[secret_settings]]
name = "RESOURCEINSTANCE"
value = "cKGfdJG87MXrLsQ"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
