specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "8Fy7CQORKsLEvdeRxRIu1ud2P"

[[secret_settings]]
name = "RESOURCEINSTANCE"
value = "w_MGW9aFOMtEXqQ"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
