specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "SkrYTz4DUUO0mc8eUAVK2P0md"

[[secret_settings]]
name = "RESOURCEINSTANCE"
value = "jRdeCkQr215bMoA"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
