specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "-vccndEsP92WB_hGbCtMa0OCB"

[[secret_settings]]
name = "RESOURCEINSTANCE"
value = "BSvqlQ7HweOPMxA"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
