specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "Kg492BWYDEJvVis7VgLeaxu2L"

[[secret_settings]]
name = "RESOURCEINSTANCE"
value = "jHsvPxjKVkIMWAQ"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
