specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "bRW4FTnvAmOVbXgUOfQ_fpF2w"

[[secret_settings]]
name = "RESOURCEINSTANCE"
value = "ASus4C15bGSBFMg"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
