specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "13KytvtT3X2L9Jsy0pdx6gn6V"

[[secret_settings]]
name = "RESOURCEINSTANCE"
value = "MunDamZHsMZagyA"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
