specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "EJlI3Ghjl2UM"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "DkJFAMUi_6Cwb"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

