specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "s3jH_spoExk8"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "xWOCOIdPKrglV"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

