specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "QZpcLoZyDF3A"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "1C0QSvtHUVWCW"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

