specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "B8E_4Yqi3J5Q"

[[secret_settings]]
name = "STORAGEINSTANCE"
value = "JbPCEp4CK8cOI"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

