specversion = "0.2"

[[secret_settings]]
name = "FILEPATH"
value = "jzWQjjKjOX8zPkwReaeFiG9I"

[[secret_settings]]
name = "STREAMER_API"
value = "Q1iyYGSWId4pXsE7Juzf3WlvhWx4vIK4XPRrUezr7goc8XsF8OKacwWFPmGXek5smMFLGezrns4UsZ9AHgObF3Ck"

[[capability]]
resource = "keyvalue.filesystem"
name = "streamer"

[[capability]]
resource = "http"
name = "streamer-rest-api"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

