specversion = "0.2"

[[secret_settings]]
name = "FILEPATH"
value = "4-faLmVghG6ByZ4amoLVhy4A"

[[secret_settings]]
name = "STREAMER_API"
value = "nu91grBj1fWZkWF3tSrItcK4MJXTrN7L_lc50eqk9su-CyGFiq2Gp-4XZYD-sOLX-d-5mnLIh88Ru7nBy9yDttJY"

[[capability]]
resource = "keyvalue.filesystem"
name = "streamer"

[[capability]]
resource = "http"
name = "streamer-rest-api"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

