specversion = "0.2"

[[secret_settings]]
name = "FILEPATH"
value = "GVvtS8OTA2POck6j89N719fE"

[[secret_settings]]
name = "STREAMER_API"
value = "4_f_-NCl9-Pa_OGllAK3uYG4_d2jUqSU-VPrz1uEV4oHB_JTm40i_98btzfr9Xe7y31yTpPrw8uHBCYW9vwjhuNU"

[[capability]]
resource = "keyvalue.filesystem"
name = "streamer"

[[capability]]
resource = "http"
name = "streamer-rest-api"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

