specversion = "0.2"

[[secret_settings]]
name = "FILEPATH"
value = "lrtB-cpAIUbZNJROpESSv0gG"

[[secret_settings]]
name = "STREAMER_API"
value = "uuwtM0m4XcOA4NJdVgRw4tuklkodVNJajOFYtCEqoaROb4NLHSE5IrJz9ixVWWy-HqfGkRFEPcdWbuYVxFA5Y448"

[[capability]]
resource = "keyvalue.filesystem"
name = "streamer"

[[capability]]
resource = "http"
name = "streamer-rest-api"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

