specversion = "0.2"

[[secret_settings]]
name = "FILEPATH"
value = "fboqd7bWnPgwks69sNKGY7Xs"

[[secret_settings]]
name = "STREAMER_API"
value = "gp9itsZ-3PGVsfsa2reCTviI6gvZ50tWfxniionWV8Y_TfmOjoMjvm2Wib_6-3fOefHLBr7mJrY1iJ9ez_Ii01HY"

[[capability]]
resource = "keyvalue.filesystem"
name = "streamer"

[[capability]]
resource = "http"
name = "streamer-rest-api"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

