specversion = "0.2"

[[secret_settings]]
name = "FILEPATH"
value = "2MSCOqM3PGEGQcUw8wjPNhac"

[[secret_settings]]
name = "STREAMER_API"
value = "jTySi9BEdGQ4aESOaWOM7mMszM4AP9GkM25RmtA00bQjaESb0nXPoCSoHcbMedMpPaVDjstojbYjMT2XjlWU7Vzc"

[[capability]]
resource = "keyvalue.filesystem"
name = "streamer"

[[capability]]
resource = "http"
name = "streamer-rest-api"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

