specversion = "0.2"

[[secret_settings]]
name = "FILEPATH"
value = "io0CDz2ASeGBPiYcIOd2f5ts"

[[secret_settings]]
name = "STREAMER_API"
value = "hijSSxrJNrZL1I8D39ne6BCPkVENwiYM6R8uaF_TOgypQ1I8D9kydPpPF1vQWV4HTTjuI6O_S39hQh54Gqo3GcUQ"

[[capability]]
resource = "keyvalue.filesystem"
name = "streamer"

[[capability]]
resource = "http"
name = "streamer-rest-api"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

