specversion = "0.2"

[[secret_settings]]
name = "FILEPATH"
value = "FFsBYL20mbqwpGzpkXXE8-sU"

[[secret_settings]]
name = "STREAMER_API"
value = "9TMvClTWOOUj6NatSP9bMtaseO0WrwZ4Wu6huVTDk4mgG6Oh0VrUYuD_5j3xIoAR5JuTRtK0kWvX0asdPqDhBsSw"

[[capability]]
resource = "keyvalue.filesystem"
name = "streamer"

[[capability]]
resource = "http"
name = "streamer-rest-api"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

