specversion = "0.2"

[[secret_settings]]
name = "FILEPATH"
value = "I4LNzrTGbOsvoPdEnyYREGdU"

[[secret_settings]]
name = "STREAMER_API"
value = "--oyhzicM0cS4-1Yt2GyUh8Cbv22GPMnNl1DuxDl7yd0twfuAxpUmVsTJomXY18vMnlpLNN9nld-A_A8ommaOhpQ"

[[capability]]
resource = "keyvalue.filesystem"
name = "streamer"

[[capability]]
resource = "http"
name = "streamer-rest-api"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

