specversion = "0.2"

[[secret_settings]]
name = "FILEPATH"
value = "rkzG57B71396TEZCWGaqD8dg"

[[secret_settings]]
name = "STREAMER_API"
value = "T-EQzV6QHb7BXpAJheGjpwka1KLbsZrtSZmF_lj2_v3axpAcm0Pg6ZmryeuF3fzsxFJBl4Lqov_aB478Mx4G5ps4"

[[capability]]
resource = "http"
name = "streamer-rest-api"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

