specversion = "0.2"

[[secret_settings]]
name = "FILEPATH"
value = "lJn5LbPSE1Gxgx8UrF7Ra_ck"

[[secret_settings]]
name = "STREAMER_API"
value = "PeUuidENw7EyhtakT1yIq2nCpJIRDNXhPoDk7VNL1ZvWsCnxURbLhtaXU-yPA9fgN4pPvQJIifM138ehV1aSqik4"

[[capability]]
resource = "keyvalue.filesystem"
name = "streamer"

[[capability]]
resource = "http"
name = "streamer-rest-api"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

