specversion = "0.2"

[[secret_settings]]
name = "FILEPATH"
value = "GcQoNQ9FP1UpLRS0ST9ecml8"

[[secret_settings]]
name = "STREAMER_API"
value = "W0BQgz6enhqFXQ8TPgQFGt4ZeloOxVhUBFsrDkzJidlYXT4PToJGzU5MZ1JQTFrIWlE5A5mABNtXBC8fEg44fgoo"

[[capability]]
resource = "keyvalue.filesystem"
name = "streamer"

[[capability]]
resource = "http"
name = "streamer-rest-api"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

