specversion = "0.2"

[[secret_settings]]
name = "FILEPATH"
value = "2IXVApDcGLwPw0V9fmtEp1_c"

[[secret_settings]]
name = "STREAMER_API"
value = "r4oIlyIgO1DIkEznPJrn4TZMJTMrEYqfAxEtZ8yCNl9DTTUzPytCJxPJcFdTLxTzBzUFL_pXMy5HTFF3iftLQi8c"

[[capability]]
resource = "keyvalue.filesystem"
name = "streamer"

[[capability]]
resource = "http"
name = "streamer-rest-api"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

