specversion = "0.2"

[[secret_settings]]
name = "FILEPATH"
value = "bBRlzhCNG2xIhDjkyU4s1Fmo"

[[secret_settings]]
name = "STREAMER_API"
value = "hHPJlcY7fzdBKCoiXFuUQCJibgWYCyoKR2jJBoRMPzZBbyoahhHXDlB2cwWYassLTWgtBJ9QlR4gYfDsndFGOQdo"

[[capability]]
resource = "http"
name = "streamer-rest-api"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

