specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "u-vVv2J7r_uc--A"

[[secret_settings]]
name = "DHTINSTANCE"
value = "Ju_r-9zpMSZtun16xLo8"

[[capability]]
resource = "keyvalue.filesystem"
name = "resolver_1"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
