specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "ZI72J7zWQjATdSQ"

[[secret_settings]]
name = "DHTINSTANCE"
value = "vEAF1Jw7j88DYWI3gVIk"

[[capability]]
resource = "keyvalue.filesystem"
name = "resolver_1"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
