specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "PgcehC5HFN17qUw"

[[secret_settings]]
name = "DHTINSTANCE"
value = "AxBZe248x12OLVthqBT8"

[[capability]]
resource = "keyvalue.filesystem"
name = "resolver_1"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
