specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "GdXQnvsjENb7lhA"

[[secret_settings]]
name = "DHTINSTANCE"
value = "nxws8l38rzoHU6gFwypE"

[[capability]]
resource = "keyvalue.filesystem"
name = "resolver_1"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
