specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "7PBCQPGj1EH29bA"

[[secret_settings]]
name = "DHTINSTANCE"
value = "fG80t5LiZVDg_HoE5Yw8"

[[capability]]
resource = "keyvalue.filesystem"
name = "resolver_1"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
