specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "GJT5TOqu9diZF7Q"

[[secret_settings]]
name = "DHTINSTANCE"
value = "RcoU0O8Mc77-LlsnRSfc"

[[capability]]
resource = "keyvalue.filesystem"
name = "resolver_1"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
