specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "C0j8-yDV07V_Ugw"

[[secret_settings]]
name = "DHTINSTANCE"
value = "L1fYhlrA8c8Ta-quYDA8"

[[capability]]
resource = "keyvalue.filesystem"
name = "resolver_1"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
