specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "nQ7iezN3oG7cjkg"

[[secret_settings]]
name = "DHTINSTANCE"
value = "P2ahkuw38H87wOgeXZGI"

[[capability]]
resource = "keyvalue.filesystem"
name = "resolver_1"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
