specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "7Ohc3NVthq8uJ3g"

[[secret_settings]]
name = "DHTINSTANCE"
value = "mCYfMaXbK2R6M08SIxNk"

[[capability]]
resource = "keyvalue.filesystem"
name = "resolver_1"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
