specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "sTr6sNJ7srlQSFw"

[[secret_settings]]
name = "DHTINSTANCE"
value = "48ar9F7AHMyti_82hlls"

[[capability]]
resource = "keyvalue.filesystem"
name = "resolver_1"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
