specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "EP78xRNndryOCxA"

[[secret_settings]]
name = "DHTINSTANCE"
value = "l7thQZN8u1zDL4BTYizI"

[[capability]]
resource = "keyvalue.filesystem"
name = "resolver_1"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
