specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "Bt1LTxucTD7pMsQ"

[[secret_settings]]
name = "DHTINSTANCE"
value = "HyWV0840GH1Z-Q0oHSVo"

[[capability]]
resource = "keyvalue.filesystem"
name = "resolver_1"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
