specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "Li4LnnCGo44AXw7"

[[secret_settings]]
name = "DHTINSTANCE"
value = "8Dytxas2fIDGXy1qHkQ4"

[[capability]]
resource = "keyvalue.filesystem"
name = "resolver_1"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
