specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "3b97BkretSvlAMg"

[[secret_settings]]
name = "DHTINSTANCE"
value = "UcKpSzebGrmZDYMST8vw"

[[capability]]
resource = "keyvalue.filesystem"
name = "resolver_1"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
