specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "KGBJOdY4giICO"

[[capability]]
resource = "keyvalue.filesystem"
name = "storage_1"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_PORT = "1883"
MOSQUITTO_HOST = "localhost"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"

