specversion = "0.2"

[[secret_settings]]
name = "INSTANCE"
value = "DYKHx2EDuDJL6BJtnYordrdeSi-DgIqQXWA"

[[capability]]
resource = "keyvalue.filesystem"
name = "ServicioPublicacionesUNAV"

[[capability]]
resource = "messaging.mosquitto"
name = "messages"

[capability.configs]
MOSQUITTO_HOST = "localhost"
MOSQUITTO_PORT = "1883"

[[capability]]
resource = "configs.usersecrets"
name = "config-store"
